In [1]:
w1, w2, w3= 0.3,0.2,0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [4]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


In [5]:
weights = [w1, w2, w3]

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [8]:
crop_yield(kanto, weights)

56.8

In [9]:
crop_yield(johto, weights)

76.9

In [10]:
%time
crop_yield(unova, weights)

CPU times: total: 0 ns
Wall time: 0 ns


74.9

In [11]:
!pip install numpy --upgrade --quiet

In [12]:
import numpy as np


In [13]:
kanto = np.array([73, 67, 43])

In [14]:
kanto

array([73, 67, 43])

In [15]:
type(kanto)

numpy.ndarray

In [16]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [17]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 15.6 ms
Wall time: 95.9 ms


833332333333500000

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [19]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 0 ns
Wall time: 0 ns


32

In [20]:
%%time

np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [21]:
#2D array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
# 2D array (matrix)
climate_data.shape

(5, 3)

In [22]:
weights = np.array([w1, w2, w3])

In [23]:
# 1D array (vector)
weights.shape

(3,)

In [24]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [25]:
arr3.dtype

dtype('float64')

In [26]:
#matrix mult

In [27]:
np.matmul(climate_data, weights)


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [28]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [29]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x24bdee54110>)

In [30]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [31]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [32]:
climate_data.shape

(10000, 3)

In [33]:
weights = np.array([0.3, 0.2, 0.5])

In [34]:
yields = climate_data @ weights

In [35]:
print(yields)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]


In [36]:
yields.shape

(10000,)

In [37]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [38]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

In [39]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [40]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [41]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [42]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [43]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [44]:
arr5 = np.array([[7],[8],[9]])
arr2+arr5 

array([[ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [18, 10, 11, 12]])

In [45]:
arr5=[7,8]
arr2+arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [ ]:
arr4 = np.array([4, 5, 6, 7])

In [ ]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [ ]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
# Single element
arr3[1, 1, 2]

36.0

In [ ]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [ ]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [ ]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [ ]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [ ]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [ ]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
# Range with start, end and step
np.arange(10, 90, 3)


array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])