> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [16]:
# List of functions explained 
function1 = np.concatenate # (change this)
function2 = np.zeros
function3 = np.random.rand
function4 = np.max
function5 = np.transpose

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [14]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In this example, we have two arrays, arr1 and arr2. Here's what each array looks like:


arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6, 7],
        [8, 9, 10]]
To concatenate these arrays horizontally (along axis 1), we use the np.concatenate function:

np.concatenate((arr1, arr2), axis=1)
The function takes two arguments: the arrays to be concatenated (arr1, arr2) and the axis parameter, which is set to 1 in this case.

The resulting concatenation will be:

[[1, 2, 5, 6, 7],
 [3, 4., 8, 9, 10]]
In the output, the elements from arr1 come first, followed by the elements from arr2, resulting in a new array with a shape of (2, 5).

Note that the elements in arr1 and arr2 must have compatible shapes along the specified axis for successful concatenation.

I hope this clears up how the np.concatenate function works! Don't hesitate to ask if you have any further questions or if there's anything else I can assist you with.

Explanation about example

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]
#arr2=np.transpose(arr2)

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3.

Here, arr2 must have 2 coloumns. Otherwise concatanation will fail

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - np.zeros(shape) 

np.zeros(shape) - This function creates a NumPy array filled with zeros.

In [ ]:
import numpy as np

arr = np.zeros((2, 3))
print(arr)

In the code above, np.zeros((2, 3)) creates a 2D array with 2 rows and 3 columns, where all the elements are zeros.

In [17]:
import numpy as np

arr = np.zeros((4, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
import numpy as np

arr = np.zeros((3,3,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - np.random.rand(shape)

np.random.rand(shape) - This function generates random numbers from a uniform distribution between 0 and 1 in the specified shape.

In [24]:
import numpy as np

arr = np.random.rand(3, 2)
print(arr)

[[0.97339668 0.11225967]
 [0.67670893 0.0896276 ]
 [0.63344369 0.97651281]]


In the code above, np.random.rand(3, 2) generates a 2D array with 3 rows and 2 columns containing random numbers between 0 and 1.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 -np.max(array)

np.max(array) - This function returns the maximum value in a NumPy array.

In [25]:
import numpy as np

arr = np.array([5, 3, 9, 1, 7])
max_val = np.max(arr)
print(max_val)

9


In the code above, np.max(arr) finds the maximum value within the array [5, 3, 9, 1, 7] and assigns it to the max_val variable.

Explanation about example

In [26]:
import numpy as np

arr = np.array([])
max_val = np.max(arr)
print(max_val)

ValueError: zero-size array to reduction operation maximum which has no identity

Explanation about example (why it breaks and how to fix it)

### explanation:
there should be some value or the array must be initialized

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.transpose(array)

np.transpose(array) - This function transposes a 2D NumPy array by swapping its rows and columns.

In [29]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed = np.transpose(arr)
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In the code above, np.transpose(arr) transposes the 2D array arr, resulting in a new array with its rows and columns interchanged.

I hope these examples help you understand and utilize these NumPy functions! Let me know if you have any further questions or if there's anything else I can assist you with.

Explanation about example

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>